# Generated by Django 4.0.3 on 2022-03-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
